CREATE TABLE IF NOT EXISTS "healthcare"."metrics" (
    
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(64) NOT NULL, 
    metric_type VARCHAR(64) NOT NULL, 
    data JSONB NOT NULL, 
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(entity_name, metric_type)
);

GRANT ALL ON "healthcare"."metrics" TO anon, authenticated, service_role;
